FROM alpine:3.15.2

# We'll likely need to add SSL root certificates
RUN apk --no-cache add ca-certificates

ADD media_service /usr/local/bin/media_service

WORKDIR /usr/local/bin

CMD ["./media_service"]
