###
GET http://localhost:8080/mediaserver/image/Y2xvdWQucGMtemllZ2VydC5kZQ==.NHw3MjgyNXw2ZDQ4ZTVmZDhkNWEwNTNmZDkzZjUxNzFmZTA0NzM2NjYzMjdkNmY3MTljZDNlMmYyYjFmNGE1NDVmYjA5MGZk/64x64?crop=true
Accept: application/json
Host: cloud.pc-ziegert.de
X-Forwarded-For: 192.168.2.24

###
GET http://localhost:8084/healthz
Accept: application/json

###
GET http://localhost:8084/readyz

###
GET http://localhost:8084/startz

###
GET http://localhost:8084/metrics
Accept: text/plain
Accept-Encoding: deflate
