###
GET http://localhost:8084/mediaserver/image/c3RhZ2luZy5kcmFjb29uLmNvbQ==.NDU0OXwxMTI1MzY1fGMxMjNhMDEyZDMzNTE3Yjk3ODc1MDk4Yjg4YmJhZGExYzlmNzBiYTUyMTM5M2UzMzA3MWFmNTQxMTI4MzEzNWI=/64x64?crop=true
Accept: application/json
X-Dracoon-Forwarded-Proto: https
X-Dracoon-Forwarded-Host: staging.dracoon.com
X-Dracoon-Forwarded-Port: 443
X-Dracoon-Client-Address: 127.0.0.1
X-Dracoon-Client-User-Agent: Test

###
GET http://localhost:8084/healthz
Accept: application/json

###
GET http://localhost:8084/readyz

###
GET http://localhost:8084/startz

###
GET http://localhost:8084/metrics
Accept: text/plain
Accept-Encoding: deflate
