/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Request model for updating user's metadata
type UpdateUserRequest struct {
	// User first name
	FirstName string `json:"firstName,omitempty"`
	// User last name
	LastName string `json:"lastName,omitempty"`
	// &#128640; Since v4.13.0  Username
	UserName string `json:"userName,omitempty"`
	// Email
	Email string `json:"email,omitempty"`
	// User is locked:  * `false` - unlocked  * `true` - locked    User is locked and can not login anymore.
	IsLocked bool `json:"isLocked,omitempty"`
	// Phone number
	Phone string `json:"phone,omitempty"`
	// IETF language tag
	ReceiverLanguage string                     `json:"receiverLanguage,omitempty"`
	Expiration       *ObjectExpiration          `json:"expiration,omitempty"`
	AuthData         *UserAuthDataUpdateRequest `json:"authData,omitempty"`
	// &#128679; Deprecated since v4.18.0  Job title
	Title string `json:"title,omitempty"`
	// &#128679; Deprecated since v4.7.0  User lock status:  * `0` - locked  * `1` - Web access allowed  * `2` - Web and mobile access allowed    Please use `isLocked` instead.
	LockStatus int32 `json:"lockStatus,omitempty"`
	// &#128679; Deprecated since v4.12.0  Gender  Do NOT use `gender`! It will be ignored.
	Gender string `json:"gender,omitempty"`
	// &#128679; Deprecated since v4.13.0  Authentication methods:  * `sql`  * `active_directory`  * `radius`  * `openid`  use `authData` instead
	AuthMethods []UserAuthMethod `json:"authMethods,omitempty"`
}
