/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Request model for generating presigned URLs
type GeneratePresignedUrlsRequest struct {
	// `Content-Length` header size for each presigned URL (in bytes)  *MUST* be >= 5 MB except the last part.
	Size int64 `json:"size"`
	// First part number of a range of requested presigned URLs (for S3 it is: `1`)
	FirstPartNumber int32 `json:"firstPartNumber"`
	// Last part number of a range of requested presigned URLs
	LastPartNumber int32 `json:"lastPartNumber"`
}
