/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// Deleted node information (Deleted node can be a folder or file)
type DeletedNodeSummary struct {
	// Parent node ID (room or folder)
	ParentId int64 `json:"parentId"`
	// Parent node path  `/` if node is a root node (room)
	ParentPath string `json:"parentPath"`
	// Node name
	Name string `json:"name"`
	// Node type
	Type_ string `json:"type"`
	// Number of deleted versions of this file
	CntVersions int32 `json:"cntVersions"`
	// First deleted version
	FirstDeletedAt time.Time `json:"firstDeletedAt"`
	// Last deleted version
	LastDeletedAt time.Time `json:"lastDeletedAt"`
	// Node ID of last deleted version
	LastDeletedNodeId int64 `json:"lastDeletedNodeId"`
	// &#128640; Since v4.22.0  Time the node was created on external file system
	TimestampCreation time.Time `json:"timestampCreation,omitempty"`
	// &#128640; Since v4.22.0  Time the content of a node was last modified on external file system
	TimestampModification time.Time `json:"timestampModification,omitempty"`
}
