/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// User lockout information
type UserLockout struct {
	// Determines whether user lockout is enabled
	Enabled bool `json:"enabled"`
	// Maximum allowed number of failed login attempts
	MaxNumberOfLoginFailures int32 `json:"maxNumberOfLoginFailures,omitempty"`
	// Amount of minutes a user has to wait to make another login attempt after `maxNumberOfLoginFailures` has been exceeded
	LockoutPeriod int32 `json:"lockoutPeriod,omitempty"`
}
