/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// System information (default language and authentication methods)
type SystemInfo struct {
	// System default language  cf. [RFC 5646](https://tools.ietf.org/html/rfc5646)
	LanguageDefault string `json:"languageDefault"`
	// &#128640; Since v4.13.0  Defines if login fields should be hidden
	HideLoginInputFields bool `json:"hideLoginInputFields"`
	// &#128640; Since v4.14.0  List of S3 Hosts for CSP header
	S3Hosts []string `json:"s3Hosts"`
	// &#128640; Since v4.15.0  Determines whether S3 direct upload is enforced or not
	S3EnforceDirectUpload bool `json:"s3EnforceDirectUpload"`
	// &#128640; Since v4.21.0  Defines if S3 is used as storage backend
	UseS3Storage bool `json:"useS3Storage"`
	// &#128679; Deprecated since v4.13.0  Authentication methods:  * `sql`  * `active_directory`  * `radius`  * `openid`  use `authData` instead
	AuthMethods []AuthMethod `json:"authMethods"`
}
