/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// Webhook information
type Webhook struct {
	// ID
	Id int64 `json:"id"`
	// Name
	Name string `json:"name"`
	// URL
	Url string `json:"url"`
	// Secret; used for event message signatures
	Secret string `json:"secret,omitempty"`
	// Is enabled
	IsEnabled bool `json:"isEnabled"`
	// Expiration date / time
	ExpireAt time.Time `json:"expireAt"`
	// List of names of event types
	EventTypeNames []string `json:"eventTypeNames"`
	// Creation date
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy *UserInfo `json:"createdBy,omitempty"`
	// Modification date
	UpdatedAt time.Time `json:"updatedAt"`
	UpdatedBy *UserInfo `json:"updatedBy,omitempty"`
	// Last HTTP status code when a webhook is disabled due to delivery failures
	FailStatus int32 `json:"failStatus,omitempty"`
}
