/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Third-party dependency information
type ThirdPartyDependenciesData struct {
	// Third party dependencies id
	Id string `json:"id"`
	// Third party dependencies name
	Name string `json:"name"`
	// Third party dependencies url
	Url string `json:"url"`
	// Third party dependencies description
	Description string `json:"description"`
	// Third party dependencies groupId
	GroupId string `json:"groupId"`
	// Third party dependencies artifactId
	ArtifactId string `json:"artifactId"`
	// Third party dependencies version
	Version string `json:"version"`
	// Third party dependencies type
	Type_ string `json:"type"`
	// Third party dependencies licenses type
	Licenses []string `json:"licenses"`
}
