/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// Log event information
type LogEvent struct {
	// Event ID
	Id int64 `json:"id"`
	// Event timestamp
	Time time.Time `json:"time"`
	// Unique identifier for the user
	UserId int64 `json:"userId"`
	// Event description
	Message string `json:"message"`
	// Operation type ID
	OperationId int32 `json:"operationId,omitempty"`
	// Operation name
	OperationName string `json:"operationName,omitempty"`
	// Operation status:  * `0` - Success  * `2` - Error
	Status int32 `json:"status,omitempty"`
	// Client
	UserClient string `json:"userClient,omitempty"`
	// Unique identifier for the customer
	CustomerId int64 `json:"customerId,omitempty"`
	// Username
	UserName string `json:"userName,omitempty"`
	// User IP
	UserIp string `json:"userIp,omitempty"`
	// Auth parent source ID
	AuthParentSource string `json:"authParentSource,omitempty"`
	// Auth parent target ID
	AuthParentTarget string `json:"authParentTarget,omitempty"`
	// Object ID 1
	ObjectId1 int64 `json:"objectId1,omitempty"`
	// Object type 1
	ObjectType1 int32 `json:"objectType1,omitempty"`
	// Object name 1
	ObjectName1 string `json:"objectName1,omitempty"`
	// Object ID 2
	ObjectId2 int64 `json:"objectId2,omitempty"`
	// Object type 2
	ObjectType2 int32 `json:"objectType2,omitempty"`
	// Object name 2
	ObjectName2 string `json:"objectName2,omitempty"`
	// Attribute 1
	Attribute1 string `json:"attribute1,omitempty"`
	// Attribute 2
	Attribute2 string `json:"attribute2,omitempty"`
	// Attribute 3
	Attribute3 string `json:"attribute3,omitempty"`
}
