/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Room information
type LastAdminUserRoom struct {
	// Room ID
	Id int64 `json:"id"`
	// Room name
	Name string `json:"name"`
	// Parent node path  `/` if node is a root node (room)
	ParentPath string `json:"parentPath"`
	// Determines whether user is last admin of a room due to being the last member of last admin group
	LastAdminInGroup bool `json:"lastAdminInGroup"`
	// Parent room ID
	ParentId int64 `json:"parentId,omitempty"`
	// ID of the last admin group where the user is the only remaining member  (returned only if `lastAdminInGroup` is `true`)
	LastAdminInGroupId int64 `json:"lastAdminInGroupId,omitempty"`
}
