/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// Software version information
type SoftwareVersionData struct {
	// REST API version
	RestApiVersion string `json:"restApiVersion"`
	// DRACOON server version
	SdsServerVersion string `json:"sdsServerVersion"`
	// Build date
	BuildDate time.Time `json:"buildDate"`
	// Revision number
	ScmRevisionNumber string `json:"scmRevisionNumber"`
	// &#128640; Since v4.24.0  Determines if the DRACOON Core is deployed in the cloud environment
	IsDracoonCloud bool `json:"isDracoonCloud,omitempty"`
}
