/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// Private key container
type PrivateKeyContainer struct {
	// Version
	Version string `json:"version"`
	// Private key
	PrivateKey string `json:"privateKey"`
	// &#128640; Since v4.24.0  Creation date
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// &#128640; Since v4.24.0  Created by user
	CreatedBy int64 `json:"createdBy,omitempty"`
}
