/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// Upload Share information
type UploadShare struct {
	// Share ID
	Id int64 `json:"id"`
	// Alias name
	Name string `json:"name"`
	// Target room or folder ID
	TargetId int64 `json:"targetId"`
	// Is share protected by password
	IsProtected bool `json:"isProtected"`
	// Share access key to generate secure link
	AccessKey string `json:"accessKey"`
	// Creation date
	CreatedAt time.Time `json:"createdAt"`

	CreatedBy *UserInfo `json:"createdBy"`
	// Modification date
	UpdatedAt time.Time `json:"updatedAt,omitempty"`

	UpdatedBy *UserInfo `json:"updatedBy,omitempty"`
	// Expiration date
	ExpireAt time.Time `json:"expireAt,omitempty"`
	// Path to shared upload node
	TargetPath string `json:"targetPath,omitempty"`
	// Encryption state
	IsEncrypted bool `json:"isEncrypted,omitempty"`
	// User notes
	Notes string `json:"notes,omitempty"`
	// &#128640; Since v4.11.0  Internal notes
	InternalNotes string `json:"internalNotes,omitempty"`
	// Number of days after which uploaded files expire
	FilesExpiryPeriod int32 `json:"filesExpiryPeriod,omitempty"`
	// Total amount of existing files uploaded with this share.
	CntFiles int32 `json:"cntFiles,omitempty"`
	// Total amount of uploads conducted with this share.
	CntUploads int32 `json:"cntUploads,omitempty"`
	// Allow display of already uploaded files
	ShowUploadedFiles bool `json:"showUploadedFiles,omitempty"`
	// Upload Share URL
	DataUrl string `json:"dataUrl,omitempty"`
	// Maximal amount of files to upload
	MaxSlots int32 `json:"maxSlots,omitempty"`
	// Maximal total size of uploaded files (in bytes)
	MaxSize int64 `json:"maxSize,omitempty"`
	// Node type
	TargetType string `json:"targetType,omitempty"`
	// &#128640; Since v4.11.0  Show creator first and last name.
	ShowCreatorName bool `json:"showCreatorName,omitempty"`
	// &#128640; Since v4.11.0  Show creator email address.
	ShowCreatorUsername bool `json:"showCreatorUsername,omitempty"`
	// &#128679; Deprecated since v4.20.0  Notify creator on every upload.
	NotifyCreator bool `json:"notifyCreator"`
	// &#128679; Deprecated since v4.11.0  CSV string of recipient email addresses
	Recipients string `json:"recipients,omitempty"`
	// &#128679; Deprecated since v4.11.0  CSV string of recipient MSISDNs
	SmsRecipients string `json:"smsRecipients,omitempty"`
}
