/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Audit user permissions report
type AuditUserPermission struct {
	// Unique identifier for the user
	UserId int64 `json:"userId"`
	// User login name
	UserLogin string `json:"userLogin"`
	// User first name
	UserFirstName string `json:"userFirstName"`
	// User last name
	UserLastName string `json:"userLastName"`

	Permissions *NodePermissions `json:"permissions"`
}
