/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// System defaults
type SystemDefaults struct {
	// Define which language should be default.
	LanguageDefault string `json:"languageDefault,omitempty"`
	// Default expiration period for Download Shares in days.
	DownloadShareDefaultExpirationPeriod int32 `json:"downloadShareDefaultExpirationPeriod,omitempty"`
	// Default expiration period for Upload Shares in days.
	UploadShareDefaultExpirationPeriod int32 `json:"uploadShareDefaultExpirationPeriod,omitempty"`
	// Default expiration period for all uploaded files in days.
	FileDefaultExpirationPeriod int32 `json:"fileDefaultExpirationPeriod,omitempty"`
	// &#128640; Since v4.12.0  Defines if new users get the role Non Member Viewer by default
	NonmemberViewerDefault bool `json:"nonmemberViewerDefault,omitempty"`
	// &#128640; Since v4.13.0  Defines if login fields should be hidden
	HideLoginInputFields bool `json:"hideLoginInputFields,omitempty"`
}
