/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Request model for updating a S3 configuration
type S3ConfigUpdateRequest struct {
	// S3 object storage bucket URL
	BucketUrl string `json:"bucketUrl,omitempty"`
	// Access Key ID
	AccessKey string `json:"accessKey,omitempty"`
	// Secret Access Key
	SecretKey string `json:"secretKey,omitempty"`
	// S3 region
	Region string `json:"region,omitempty"`
	// &#128679; Deprecated since v4.24.0  S3 object storage endpoint URL  use `bucketUrl` instead
	EndpointUrl string `json:"endpointUrl,omitempty"`
	// &#128679; Deprecated since v4.24.0  S3 bucket name  use `bucketUrl` instead
	BucketName string `json:"bucketName,omitempty"`
}
