/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// OAuth authorization
type OAuthAuthorization struct {
	// ID of the OAuth client
	ClientId string `json:"clientId"`
	// Name, which is shown at the client configuration and authorization.
	ClientName string `json:"clientName"`
	// &#128640; Since v4.12.0  User agent category.
	UserAgentCategory string `json:"userAgentCategory"`
	// &#128640; Since v4.12.0  ID of the OAuth authorization
	Id int64 `json:"id,omitempty"`
	// &#128640; Since v4.12.0  Determines whether client is a standard client.
	IsStandard bool `json:"isStandard,omitempty"`
	// &#128640; Since v4.13.0  Creation date of the authorization
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// &#128640; Since v4.13.0  Usage date of the authorization  (Time of last usage.)
	UsedAt time.Time `json:"usedAt,omitempty"`
	// Expiration date of the authorization
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
	// &#128640; Since v4.12.0  User agent type.
	UserAgentType string `json:"userAgentType,omitempty"`
	// &#128640; Since v4.12.0  User agent OS.
	UserAgentOs string `json:"userAgentOs,omitempty"`
	// &#128640; Since v4.12.0  User agent info.
	UserAgentInfo string `json:"userAgentInfo,omitempty"`
	// &#128640; Since v4.25.0  Determines whether authorization matches the one from Authorization Header
	IsCurrentAuthorization bool `json:"isCurrentAuthorization,omitempty"`
}
