/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// Audit node report
type AuditNodeResponse struct {
	// Node ID
	NodeId int64 `json:"nodeId"`
	// Node name
	NodeName string `json:"nodeName"`
	// Parent node path  `/` if node is a root node (room)
	NodeParentPath string `json:"nodeParentPath"`
	// Number of direct children  (no recursion; for rooms only)
	NodeCntChildren int32 `json:"nodeCntChildren"`
	// List of assigned users with permissions
	AuditUserPermissionList []AuditUserPermission `json:"auditUserPermissionList"`
	// Parent node ID (room or folder)
	NodeParentId int64 `json:"nodeParentId,omitempty"`
	// Node size in byte
	NodeSize int64 `json:"nodeSize,omitempty"`
	// Retention period for deleted nodes in days
	NodeRecycleBinRetentionPeriod int32 `json:"nodeRecycleBinRetentionPeriod,omitempty"`
	// Quota in byte
	NodeQuota int64 `json:"nodeQuota,omitempty"`
	// Encryption state
	NodeIsEncrypted bool `json:"nodeIsEncrypted,omitempty"`
	// Is activities log active (for rooms only)
	NodeHasActivitiesLog bool `json:"nodeHasActivitiesLog,omitempty"`
	// Creation date
	NodeCreatedAt time.Time `json:"nodeCreatedAt,omitempty"`
	NodeCreatedBy *UserInfo `json:"nodeCreatedBy,omitempty"`
	// Modification date
	NodeUpdatedAt time.Time `json:"nodeUpdatedAt,omitempty"`
	NodeUpdatedBy *UserInfo `json:"nodeUpdatedBy,omitempty"`
	// &#128679; Deprecated since v4.10.0  Is recycle bin active (for rooms only)  Recycle bin is always on (disabling is not possible).
	NodeHasRecycleBin bool `json:"nodeHasRecycleBin,omitempty"`
}
