/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// User Authentication Data
type UserAuthData struct {
	// Authentication method    Authentication methods:  * `basic`  * `active_directory`  * `radius`  * `openid`
	Method string `json:"method"`
	// User login name
	Login string `json:"login,omitempty"`
	// Password (only relevant for `basic` authentication type)  *NOT* your Active Directory, OpenID or RADIUS password!
	Password string `json:"password,omitempty"`
	// Determines whether user has to change his / her password  * default: `true` for `basic` auth type  * default: `false` for `active_directory`, `openid` and `radius` auth types
	MustChangePassword bool `json:"mustChangePassword,omitempty"`
	// ID of the user's Active Directory.
	AdConfigId int32 `json:"adConfigId,omitempty"`
	// ID of the user's OIDC provider.
	OidConfigId int32 `json:"oidConfigId,omitempty"`
}
