/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Request model for updating user account information
type UpdateUserAccountRequest struct {
	// &#128640; Since v4.13.0  Username
	UserName string `json:"userName,omitempty"`
	// Accept EULA  Present, if EULA is system global active.  cf. `GET system/config/settings/general` - `eulaEnabled`  If accepted can not be undone.
	AcceptEULA bool `json:"acceptEULA,omitempty"`
	// User first name
	FirstName string `json:"firstName,omitempty"`
	// User last name
	LastName string `json:"lastName,omitempty"`
	// Email
	Email string `json:"email,omitempty"`
	// Phone number
	Phone string `json:"phone,omitempty"`
	// &#128640; Since v4.20.0  IETF language tag
	Language string `json:"language,omitempty"`
	// &#128679; Deprecated since v4.18.0  Job title
	Title string `json:"title,omitempty"`
	// &#128679; Deprecated since v4.13.0  User login name
	Login string `json:"login,omitempty"`
	// &#128679; Deprecated since v4.12.0  Gender  Do NOT use `gender`! It will be ignored.
	Gender string `json:"gender,omitempty"`
}
