/*
 * DRACOON API
 *
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * API version: 4.33.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Request model for updating a list of Download Shares
type UpdateUploadSharesBulkRequest struct {
	Expiration *ObjectExpiration `json:"expiration,omitempty"`
	// Show creator first and last name.
	ShowCreatorName bool `json:"showCreatorName,omitempty"`
	// Show creator email address.
	ShowCreatorUsername bool `json:"showCreatorUsername,omitempty"`
	// Allow display of already uploaded files
	ShowUploadedFiles bool `json:"showUploadedFiles,omitempty"`
	// Maximal amount of files to upload
	MaxSlots int32 `json:"maxSlots,omitempty"`
	// Set 'true' to reset 'maxSlots' for Upload Share
	ResetMaxSlots bool `json:"resetMaxSlots,omitempty"`
	// Maximal total size of uploaded files (in bytes)
	MaxSize int64 `json:"maxSize,omitempty"`
	// Set 'true' to reset 'maxSize' for Upload Share
	ResetMaxSize bool `json:"resetMaxSize,omitempty"`
	// Number of days after which uploaded files expire
	FilesExpiryPeriod int32 `json:"filesExpiryPeriod,omitempty"`
	// Set 'true' to reset 'filesExpiryPeriod' for Upload Share
	ResetFilesExpiryPeriod bool `json:"resetFilesExpiryPeriod,omitempty"`
	// List of ids
	ObjectIds []int64 `json:"objectIds"`
}
